export const RECEIVE_DASHBOARD_STATISTICS = "RECEIVE_DASHBOARD_STATISTICS"
export const RECEIVE_RANDOM_SITE_DATA = "RECEIVE_RANDOM_SITE_DATA"
export const RECIEVE_RANDOM_SITE_LIST = "RECIEVE_RANDOM_SITE_LIST"
export const RECIEVE_RANDOM_SITE_SINGLE = "RECIEVE_RANDOM_SITE_SINGLE"
export const RECEIVE_SITE_DEVICE_LIST = "RECEIVE_SITE_DEVICE_LIST"

export const STATIC_STATE_DATA = 'STATIC_STATE_DATA' 
